workflows:
  telegram-build-workflow:
    name: Сборка Telegram в APK
    environment:
      java: 17
      vars:
        BUILD_FILE_PATH: "build.gradle"
        APP_VERSION: "1.4.3.3"
    scripts:
      - name: Проверка логов Git и наличия файла сборки
        script: |
          #!/usr/bin/env bash
          set -e
          
          if git log -1 --name-only | grep -q "$BUILD_FILE_PATH"; then
              echo "✅ Файл сборки был изменен в последнем коммите."
          fi
          
          if [ ! -f "$BUILD_FILE_PATH" ]; then
              echo "❌ ОШИБКА: Файл $BUILD_FILE_PATH не найден!"
              exit 1
          fi

      - name: Установка системных зависимостей (Python plugins)
        script: |
          #!/usr/bin/env bash
          echo "📦 Установка pyrogram..."
          pip3 install pyrogram

      - name: Подготовка локального окружения
        script: |
          #!/usr/bin/env bash
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Сборка исходников в APK-файл
        script: |
          #!/usr/bin/env bash
          chmod +x gradlew
          echo "🚀 Начинаем полную компиляцию всех файлов в APK..."
          
          ./gradlew assembleRelease -PversionName=$APP_VERSION

    artifacts:
      - "**/build/outputs/apk/**/*.apk"
      
